spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5434/library
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #      usar create-drop tambem se quiser
    properties:
      hibernate.format_sql: true
      # Formata o sql no terminal
